# -*- coding: utf-8 -*-
"""randomforest_aaple.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/116lWQl7gHCUF8JS-rCItnZZSDMWJ9MFg
"""

import yfinance as yf
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

# Download Apple stock data
def fetch_data():
    stock_data = yf.download("AAPL", start="2020-01-01", end="2023-01-01")
    return stock_data['Adj Close']

# Prepare the data
def prepare_data(data, lag=5):
    df = pd.DataFrame(data)
    df['Target'] = df['Adj Close'].shift(-lag)
    for i in range(1, lag+1):
        df[f'lag_{i}'] = df['Adj Close'].shift(i)
    df.dropna(inplace=True)
    return df

# Train Random Forest model
def train_model(df):
    X = df.drop("Target", axis=1)
    y = df['Target']

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    model = RandomForestRegressor(n_estimators=100, random_state=42)
    model.fit(X_train, y_train)

    score = model.score(X_test, y_test)
    print(f"Model Accuracy: {score:.2f}")

    return model

if __name__ == "__main__":
    data = fetch_data()
    df = prepare_data(data)
    model = train_model(df)